apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend-deployment
  labels:
    app: node-backend
spec:
  replicas: 3 # Number of copies of your app to run
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
      - name: node-app
        image: sha256:a014f0f3ee179525cda783389cb8042680903f095c595e15456c219662cc3a8b 
        ports:
        - containerPort: 3001 # The port your Node.js app listens on
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        # If you have environment variables, add them here:
        env:
        - name: NODE_ENV
          value: "production"