apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  selector:
    app: node-backend # Must match the label in your Deployment
  ports:
    - protocol: TCP
      port: 80        # The port the Service exposes externally
      targetPort: 3001 # The port your Node.js container is listening on
  type: LoadBalancer